### ISSUE TITLE
Update dependencies to JupyterLab 1.0.1

### ISSUE THREAD

**Issue by rpwagner** [globus/globus-jupyterlab#1]
@gneezyn this is the new repo for the JupyterLab extension.

Can you fork this one, and update the dependencies in `package.json` to reflect the latest JupyterLab releases? In particular, `@jupyterlab/application`, `@jupyterlab/apputils`, `@jupyterlab/filebrowser`, and `@jupyterlab/terminal`? Currently these are now at 1.0.1 after the initial 1.0 release of JupyterLab.

**Comment by NickolausDS** [comment]
Jupyterlab moved a lot since this ticket was opened! We're a few versions past this on Jupyterlab v3.3.4, and perhaps v4 in not too long!
